name: sec_pro_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  

  postgres: ^2.4.1  # Dart PostgreSQL package
  json_annotation: ^4.0.1
  http: ^0.13.4  # For HTTP requests
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0  # If you are using json_serializable

flutter:
  uses-material-design: true
